<?php
// food, drugs_and_cosmetics, clothes, charges, other, cash_machine
return [
	'match' => [
		'piotr i pawel' => 'food',
		'super - pharm' => 'drugs_and_cosmetics',
		'starbucks' => 'food',
		'klos' => 'food',
		'intermarche' => 'food',
		'zabka' => 'food',
		'bar figa' => 'food',
		'businessbar' => 'food',
		'kfc' => 'food',
		'apteka' => 'drugs_and_cosmetics',
		'mcdonalds' => 'food',
		'rossmann' => 'drugs_and_cosmetics',
		'diverse' => 'clothes',
		'pizza hut' => 'food',
		'fh cora' => 'food',
		'kebab' => 'food',
		'biedronka' => 'food',
		'arkadiusz nowakowski' => 'charges',
		'upc' => 'charges',
		'wzn' => 'charges',
		'fitness academy' => 'food',
		'burger king' => 'food',
		'pasta masta' => 'food',
		'piekarnia' => 'food',
		'carrefour' => 'food',
		'lisieckie smaki' => 'food',
		'stokrotka' => 'food',
		'restauracja' => 'food',
		'h and m' => 'clothes',
		'polska telefonia cyfrowa' => 'charges',
		'manicure & pedicure' => 'drugs_and_cosmetics',
		'manicure express' => 'drugs_and_cosmetics',
		'camaieu' => 'clothes',
		'grill point' => 'food',
		'melisa pharm' => 'drugs_and_cosmetics',
		'mega-smak' => 'food',
		'bar lala mi do' => 'food',
		'vipserv' => 'charges',
		'pyszne.pl' => 'food',
		'wypłata z bankomatu' => 'cash_machine',
		'prowizja' => 'charges',
		'opłata' => 'charges',
		'obciążenie' => 'charges',
		'tauron' => 'charges',
		'reserved' => 'clothes',
		'lidl' => 'food',
		'lambert' => 'clothes',
		'intimissimi' => 'clothes',
		'restaurant' => 'food',
		'zara' => 'clothes',
		'gatta' => 'clothes',
		'eleclerc' => 'food',
	]
];
